return {
    Russian = {
        -- Home
        Player = "Игрок",
        Languages = "Языки",
        MenuLanguage = "Язык Меню",
        Social = "Социальные сети",
        Information = "ИНФОРМАЦИЯ",
        Discord = "Дискорд",
        DiscordCopied = "Discord приглашение скопировано!",
        
        -- Main Tab
        NextDoor = "Следующая дверь",
        PrevDoor = "Предыдущая дверь",
        NextDoorKey = "Клавиша следующей двери",
        PrevDoorKey = "Клавиша предыдущей двери",
        EntityNotif = "Уведомления об энтити",
        EnableSpeedBoost = "Включить ускорение",
        SpeedBoostKey = "Клавиша ускорения",
        SpeedValue = "Значение скорости",
        UnlockJump = "Разблокировать прыжок",
        AutoLoot = "Автолут",
        LootCategories = "Категории лута",
        IgnoreShopItems = "Игнорировать товары магазина",
        Amethysts = "Аметисты",
        Batteries = "Батарейки",
        Bandages = "Бинты",
        Vitamins = "Витамины",
        Keycards = "Ключ-карты",
        
        -- Visibility Tab
        LeftTabbox = "Левая вкладка",
        ESP = "ЭСП",
        MasterESP = "Главный ЭСП",
        ItemESP = "ЭСП предметов",
        EntityESP = "ЭСП энтити",
        ShowItemNames = "Показывать имена предметов",
        Fullbright = "Полная яркость",
        SelectCategories = "Выбрать категории",
        Tracer = "Трассер",
        EnableTracers = "Включить трассеры",
        TracerCategories = "Категории трассеров",
        Colors = "Цвета",
        BreakableCrate = "Разбиваемый ящик",
        Flashlights = "Фонарики",
        Lighters = "Зажигалки",
        BulkLight = "Массовый свет",
        DeceivingDust = "Обманчивая пыль",
        Silver = "Серебро",
        Lever = "Рычаг",
        Sword = "Меч",
        Doors = "Двери",
        Gates = "Ворота",
        Vents = "Вентили",
        HidingLockers = "Шкафчики для укрытия",
        
        -- Floors Tab
        Final = "Финальное",
        FinishComputers = "Завершить компьютеры (комната 100)",
        TPNullZone = "ТП начало NullZone",
        FinishLibrary = "Завершить библиотеку",
        FinishNest = "Завершить гнездо (шахты)",
        SeekChaseEnd = "Конец преследования Seek",
        Toggles = "Переключатели",
        NoShock = "БезШока",
        AntiSnare = "Анти Ловушка",
        AntiA90 = "Анти А90/А90Б",
        AntiGlare = "Анти Блеск",
        AntiShade = "Анти Тень",
        AntiLasers = "Анти Лазеры",
        AntiVoid = "Анти Пустота",
        AntiEntity = "Анти Энтити",
        InstantInteract = "Мгновенное взаимодействие",
        AntiEntityTargets = "Цели анти энтити",
        
        -- Configs Tab
        Configuration = "Конфигурация",
        ConfigName = "Имя конфига",
        CreateConfig = "Создать конфиг",
        ConfigList = "Список конфигов",
        LoadConfig = "Загрузить конфиг",
        OverwriteConfig = "Перезаписать конфиг",
        DeleteConfig = "Удалить конфиг",
        RefreshList = "Обновить список",
        SetAutoload = "Установить как автозагрузку",
        ResetAutoload = "Сбросить автозагрузку",
        CurrentAutoload = "Текущий конфиг автозагрузки",
    },
    English = {
        -- Home
        Player = "Player",
        Languages = "Languages",
        MenuLanguage = "Menu Language",
        Social = "Social",
        Information = "INFORMATION",
        Discord = "Discord",
        DiscordCopied = "Discord invite copied!",
        
        -- Main Tab
        NextDoor = "Next Door",
        PrevDoor = "Previous Door",
        NextDoorKey = "Next Door Key",
        PrevDoorKey = "Previous Door Key",
        EntityNotif = "Entity Notifications",
        EnableSpeedBoost = "Enable Speed Boost",
        SpeedBoostKey = "Speed Boost Key",
        SpeedValue = "Speed Value",
        UnlockJump = "Unlock Jump",
        AutoLoot = "Auto Loot",
        LootCategories = "Loot Categories",
        IgnoreShopItems = "Ignore shop items",
        Amethysts = "Amethysts",
        Batteries = "Batteries",
        Bandages = "Bandages",
        Vitamins = "Vitamins",
        Keycards = "Keycards",
        
        -- Visibility Tab
        LeftTabbox = "Left Tabbox",
        ESP = "ESP",
        MasterESP = "Master ESP",
        ItemESP = "Item ESP",
        EntityESP = "Entity ESP",
        ShowItemNames = "Show Item Names",
        Fullbright = "Fullbright",
        SelectCategories = "Select Categories",
        Tracer = "Tracer",
        EnableTracers = "Enable Tracers",
        TracerCategories = "Tracer Categories",
        Colors = "Colors",
        BreakableCrate = "BreakableCrate",
        Flashlights = "Flashlights",
        Lighters = "Lighters",
        BulkLight = "BulkLight",
        DeceivingDust = "DeceivingDust",
        Silver = "Silver",
        Lever = "Lever",
        Sword = "Sword",
        Doors = "Doors",
        Gates = "Gates",
        Vents = "Vents",
        HidingLockers = "HidingLockers",
        
        -- Floors Tab
        Final = "Final",
        FinishComputers = "Finish Computers (room 100)",
        TPNullZone = "TP NullZone Start",
        FinishLibrary = "Finish Library",
        FinishNest = "Finish Nest (Mines)",
        SeekChaseEnd = "Seek Chase End",
        Toggles = "Toggles",
        NoShock = "NoShock",
        AntiSnare = "Anti Snare",
        AntiA90 = "Anti A90/A90B",
        AntiGlare = "Anti Glare",
        AntiShade = "Anti Shade",
        AntiLasers = "Anti Lasers",
        AntiVoid = "Anti Void",
        AntiEntity = "Anti Entity",
        InstantInteract = "Instant Interact",
        AntiEntityTargets = "Anti Entity Targets",
        
        -- Configs Tab
        Configuration = "Configuration",
        ConfigName = "Config name",
        CreateConfig = "Create config",
        ConfigList = "Config list",
        LoadConfig = "Load config",
        OverwriteConfig = "Overwrite config",
        DeleteConfig = "Delete config",
        RefreshList = "Refresh list",
        SetAutoload = "Set as autoload",
        ResetAutoload = "Reset autoload",
        CurrentAutoload = "Current autoload config",
    },
    Chinese = {
        -- Home
        Player = "玩家",
        Languages = "语言",
        MenuLanguage = "菜单语言",
        Social = "社交",
        Information = "信息",
        Discord = "不和谐",
        DiscordCopied = "Discord 邀请已复制！",
        
        -- Main Tab
        NextDoor = "下一扇门",
        PrevDoor = "上一扇门",
        NextDoorKey = "下一扇门按键",
        PrevDoorKey = "上一扇门按键",
        EntityNotif = "实体通知",
        EnableSpeedBoost = "启用速度提升",
        SpeedBoostKey = "速度提升按键",
        SpeedValue = "速度值",
        UnlockJump = "解锁跳跃",
        AutoLoot = "自动拾取",
        LootCategories = "战利品类别",
        IgnoreShopItems = "忽略商店物品",
        Amethysts = "紫水晶",
        Batteries = "电池",
        Bandages = "绷带",
        Vitamins = "维生素",
        Keycards = "钥匙卡",
        
        -- Visibility Tab
        LeftTabbox = "左标签框",
        ESP = "ESP",
        MasterESP = "主 ESP",
        ItemESP = "物品 ESP",
        EntityESP = "实体 ESP",
        ShowItemNames = "显示物品名称",
        Fullbright = "全亮",
        SelectCategories = "选择类别",
        Tracer = "示踪器",
        EnableTracers = "启用示踪器",
        TracerCategories = "示踪器类别",
        Colors = "颜色",
        BreakableCrate = "可破坏的箱子",
        Flashlights = "手电筒",
        Lighters = "打火机",
        BulkLight = "批量灯",
        DeceivingDust = "欺骗性尘埃",
        Silver = "银",
        Lever = "杠杆",
        Sword = "剑",
        Doors = "门",
        Gates = "大门",
        Vents = "通风口",
        HidingLockers = "隐藏柜",
        
        -- Floors Tab
        Final = "最终",
        FinishComputers = "完成计算机（房间 100）",
        TPNullZone = "传送 NullZone 开始",
        FinishLibrary = "完成图书馆",
        FinishNest = "完成巢穴（矿山）",
        SeekChaseEnd = "Seek 追逐结束",
        Toggles = "切换",
        NoShock = "无冲击",
        AntiSnare = "反陷阱",
        AntiA90 = "反 A90/A90B",
        AntiGlare = "反眩光",
        AntiShade = "反阴影",
        AntiLasers = "反激光",
        AntiVoid = "反虚空",
        AntiEntity = "反实体",
        InstantInteract = "即时交互",
        AntiEntityTargets = "反实体目标",
        
        -- Configs Tab
        Configuration = "配置",
        ConfigName = "配置名称",
        CreateConfig = "创建配置",
        ConfigList = "配置列表",
        LoadConfig = "加载配置",
        OverwriteConfig = "覆盖配置",
        DeleteConfig = "删除配置",
        RefreshList = "刷新列表",
        SetAutoload = "设置为自动加载",
        ResetAutoload = "重置自动加载",
        CurrentAutoload = "当前自动加载配置",
    },
    Ukrainian = {
        -- Home
        Player = "Гравець",
        Languages = "Мови",
        MenuLanguage = "Мова меню",
        Social = "Соціальні мережі",
        Information = "ІНФОРМАЦІЯ",
        Discord = "Дискорд",
        DiscordCopied = "Запрошення на Discord скопійовано!",
        
        -- Main Tab
        NextDoor = "Наступні двері",
        PrevDoor = "Попередні двері",
        NextDoorKey = "Клавіша наступних дверей",
        PrevDoorKey = "Клавіша попередніх дверей",
        EntityNotif = "Сповіщення про сутності",
        EnableSpeedBoost = "Увімкнути прискорення",
        SpeedBoostKey = "Клавіша прискорення",
        SpeedValue = "Значення швидкості",
        UnlockJump = "Розблокувати стрибок",
        AutoLoot = "Автозбір",
        LootCategories = "Категорії здобичі",
        IgnoreShopItems = "Ігнорувати предмети магазину",
        Amethysts = "Аметисти",
        Batteries = "Батарейки",
        Bandages = "Перев'язувальні матеріали",
        Vitamins = "Вітаміни",
        Keycards = "Карти-ключі",
        
        -- Visibility Tab
        LeftTabbox = "Ліва вкладка",
        ESP = "ESP",
        MasterESP = "Головний ESP",
        ItemESP = "ESP предметів",
        EntityESP = "ESP сутностей",
        ShowItemNames = "Показувати імена предметів",
        Fullbright = "Повна яскравість",
        SelectCategories = "Вибрати категорії",
        Tracer = "Трасер",
        EnableTracers = "Увімкнути трасери",
        TracerCategories = "Категорії трасерів",
        Colors = "Кольори",
        BreakableCrate = "Розбиваємий ящик",
        Flashlights = "Ліхтарики",
        Lighters = "Запальнички",
        BulkLight = "Масовий світло",
        DeceivingDust = "Обманюючий пил",
        Silver = "Срібло",
        Lever = "Важіль",
        Sword = "Меч",
        Doors = "Двері",
        Gates = "Ворота",
        Vents = "Вентиляційні отвори",
        HidingLockers = "Шафи для приховування",
        
        -- Floors Tab
        Final = "Фіналь",
        FinishComputers = "Завершити комп'ютери (кімната 100)",
        TPNullZone = "ТП початок NullZone",
        FinishLibrary = "Завершити бібліотеку",
        FinishNest = "Завершити гніздо (шахти)",
        SeekChaseEnd = "Кінець переслідування Seek",
        Toggles = "Перемикачі",
        NoShock = "БезШоку",
        AntiSnare = "Анти пастка",
        AntiA90 = "Анти А90/А90Б",
        AntiGlare = "Анти блиск",
        AntiShade = "Анти тінь",
        AntiLasers = "Анти лазери",
        AntiVoid = "Анти порожнеча",
        AntiEntity = "Анти сутність",
        InstantInteract = "Миттєва взаємодія",
        AntiEntityTargets = "Цілі анти сутності",
        
        -- Configs Tab
        Configuration = "Конфігурація",
        ConfigName = "Назва конфігурації",
        CreateConfig = "Створити конфіг",
        ConfigList = "Список конфігів",
        LoadConfig = "Завантажити конфіг",
        OverwriteConfig = "Перезаписати конфіг",
        DeleteConfig = "Видалити конфіг",
        RefreshList = "Оновити список",
        SetAutoload = "Встановити як автозавантаження",
        ResetAutoload = "Скинути автозавантаження",
        CurrentAutoload = "Поточна конфігурація автозавантаження",
    }
}
